data = 
  outline:
    "outline":
      "h1":"Companies"
      "accounting":
        "category":"Accounting"
        "items":
          "1":
            "name":"indinero"
            "url(href='https://indinero.com')":"https://indinero.com"
          "2":
            "name":"kissmetrics"
            "url(href='https://kissmetrics.com')":"https://www.kissmetrics.com/"
      "analytics":
        "category":"Analytics"
        "items":
          "1":
            "name":"leftronic"
            "url(href='https://beta.leftronic.com/main/')":"https://beta.leftronic.com/main/"
      "fashion":
        "category":"Fashion"
        "items":
          "1":
            "name":"fabricly"
            "url(href='http://fabricly.com')":"http://fabricly.com"